kafkaConnectionString : monkbus.cloudapp.net:9092,monkbus.cloudapp.net:9093,monkbus.cloudapp.net:9094
mongoConnectionString : monkdb.cloudapp.net:27017
dataDataBaseName: Travel 
entityCollectionName: Seattle
